batch: 16
box: 7.5
cache: ram
cls: 0.5
cos_lr: true
data: /home/zishu/workspace/code/data/yolo_dataset/dataset.yaml
degrees: 0.0
deterministic: true
device: 0
dfl: 1.5
dropout: 0.0
epochs: 100
exist_ok: true
fliplr: 0.5
flipud: 0.0
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
imgsz: 640
label_smoothing: 0.0
lr0: 0.01
lrf: 0.01
mixup: 0.0
model: yolov8s.pt
momentum: 0.937
mosaic: 1.0
name: bullseye_train
optimizer: AdamW
patience: 50
perspective: 0.0
plots: true
pretrained: true
project: runs/detect
rect: false
save: true
save_period: 10
scale: 0.5
seed: 42
shear: 0.0
single_cls: true
translate: 0.1
val: true
verbose: true
weight_decay: 0.0005
workers: 8
