batch: 12
box: 8.0
cache: ram
cls: 0.6
cos_lr: true
data: /home/zishu/workspace/code/data/yolo_dataset/dataset.yaml
degrees: 0.0
deterministic: true
device: 0
dfl: 1.8
dropout: 0.0
epochs: 150
exist_ok: true
fliplr: 0.5
flipud: 0.0
hsv_h: 0.01
hsv_s: 0.6
hsv_v: 0.3
imgsz: 960
label_smoothing: 0.0
lr0: 0.008
lrf: 0.005
mixup: 0.1
model: yolov8m.pt
momentum: 0.937
mosaic: 1.0
name: bullseye_optimized
optimizer: AdamW
patience: 60
perspective: 0.0
plots: true
pretrained: true
project: runs/detect
rect: false
save: true
save_period: 10
scale: 0.7
seed: 42
shear: 0.0
single_cls: true
translate: 0.1
val: true
verbose: true
weight_decay: 0.0005
workers: 8
